//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrossPlan
    {
        public int Id { get; set; }
        public string Year { get; set; }
        public Nullable<int> MaleParentId { get; set; }
        public Nullable<int> FemaleParentId { get; set; }
        public string Purpose { get; set; }
        public int GenusId { get; set; }
        public bool Unsuccessful { get; set; }
        public bool Reciprocal { get; set; }
        public Nullable<int> CrossTypeId { get; set; }
        public Nullable<int> OriginId { get; set; }
        public Nullable<int> SeedNum { get; set; }
        public Nullable<int> FieldPlantedNum { get; set; }
        public Nullable<int> TransplantedNum { get; set; }
        public string Note { get; set; }
        public string CrossNum { get; set; }
        public Nullable<int> GenotypeId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Genotype MaleParent { get; set; }
        public virtual Genotype FemaleParent { get; set; }
        public virtual Genus Genus { get; set; }
        public virtual CrossType CrossType { get; set; }
        public virtual Origin Origin { get; set; }
    }
}
