//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Family()
        {
            this.Genotypes = new HashSet<Genotype>();
        }
    
        public int Id { get; set; }
        public string CrossNum { get; set; }
        public int GenusId { get; set; }
        public Nullable<bool> IsReciprocal { get; set; }
        public Nullable<int> OriginId { get; set; }
        public Nullable<int> SeedNum { get; set; }
        public Nullable<int> CrossTypeId { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> FemaleParent { get; set; }
        public Nullable<int> MaleParent { get; set; }
        public string ReciprocalString { get; set; }
        public Nullable<int> BaseGenotypeId { get; set; }
        public string MaleParentOriginalName { get; set; }
        public string FemaleParentOriginalName { get; set; }
        public bool Unsuccessful { get; set; }
        public Nullable<int> FieldPlantedNum { get; set; }
        public Nullable<int> TransplantedNum { get; set; }
    
        public virtual Genus Genus { get; set; }
        public virtual CrossType CrossType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genotype> Genotypes { get; set; }
        public virtual Genotype FemaleGenotype { get; set; }
        public virtual Genotype MaleGenotype { get; set; }
        public virtual Genotype BaseGenotype { get; set; }
        public virtual Origin Origin { get; set; }
    }
}
