//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatNote
    {
        public string Other { get; set; }
        public int FlatTypeId { get; set; }
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Text { get; set; }
        public int GenotypeId { get; set; }
    
        public virtual FlatType FlatType { get; set; }
        public virtual Genotype Genotype { get; set; }
    }
}
