//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genotype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Genotype()
        {
            this.FemaleofFamilies = new HashSet<Family>();
            this.MaleofFamilies = new HashSet<Family>();
            this.Candidates = new HashSet<Candidate>();
            this.Answers = new HashSet<Answer>();
            this.MapComponents = new HashSet<MapComponent>();
            this.Notes = new HashSet<Note>();
            this.FlatNotes = new HashSet<FlatNote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SelectionNum { get; set; }
        public string GivenName { get; set; }
        public int FamilyId { get; set; }
        public string Year { get; set; }
        public string Note { get; set; }
        public string Fate { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public Nullable<bool> IsRoot { get; set; }
        public string Alias1 { get; set; }
        public string Alias2 { get; set; }
        public string OriginalName { get; set; }
        public string PatentApp { get; set; }
        public string Patent { get; set; }
        public string PatentYear { get; set; }
        public string PloidyName { get; set; }
        public Nullable<int> CrossPlanId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsPopulation { get; set; }
    
        public virtual Family Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> FemaleofFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> MaleofFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapComponent> MapComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlatNote> FlatNotes { get; set; }
    }
}
