//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MapComponent()
        {
            this.Repetitions = new HashSet<Repetition>();
            this.MapComponentYears = new HashSet<MapComponentYears>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Row { get; set; }
        public int MapId { get; set; }
        public int Rep { get; set; }
        public int PlantsInRep { get; set; }
        public Nullable<int> GenotypeId { get; set; }
        public Nullable<int> PlantNum { get; set; }
        public Nullable<bool> isSeedling { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public string Virus4 { get; set; }
        public string Virus1 { get; set; }
        public string Virus2 { get; set; }
        public string Virus3 { get; set; }
        public bool isRemoved { get; set; }
        public string PickingNumber { get; set; }
        public string CreatedYear { get; set; }
    
        public virtual Map Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repetition> Repetitions { get; set; }
        public virtual Genotype Genotype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapComponentYears> MapComponentYears { get; set; }
    }
}
