//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int Id { get; set; }
        public int GenotypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int MaterialId { get; set; }
        public int OrderId { get; set; }
        public Nullable<System.DateTime> VirusTested { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    
        public virtual Genotype Genotype { get; set; }
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
    }
}
