//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
        public int GenusId { get; set; }
        public int GrowerId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Note { get; set; }
        public bool MTARequestedProp { get; set; }
        public bool MTARequestedTest { get; set; }
        public Nullable<System.DateTime> MTAComplete { get; set; }
    
        public virtual Genus Genus { get; set; }
        public virtual Grower Grower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual Location Location { get; set; }
    }
}
