//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsCPY
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int GenusId { get; set; }
        public bool Required { get; set; }
        public Nullable<bool> Retired { get; set; }
        public string Label { get; set; }
        public int Order { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public Nullable<int> InputTypeId { get; set; }
        public Nullable<int> CurId { get; set; }
    }
}
