//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usda.PlantBreeding.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repetition
    {
        public int Id { get; set; }
        public int MapComponentId { get; set; }
        public string Note { get; set; }
        public int RepNumber { get; set; }
        public bool RBD { get; set; }
        public bool RSV { get; set; }
        public bool TSV { get; set; }
    
        public virtual MapComponent MapComponent { get; set; }
    }
}
